### ISSUE TITLE
error on merge soon after creating two datasets

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#279]
you can see this by running pybamboo tests.test_dataset:TestDataset.test_merge

the test will pass since bamboo returns the dataset id and fires off the merge in the background, but if you look at the celery log it seems like the record is not there:

```
[2012-11-14 13:26:37,682: ERROR/MainProcess] Task bamboo.core.merge._merge_datasets_task[66b6e87f-9b72-44ac-837d-ef388f2885c4] raised exception: TypeError("'NoneType' object has no attribute '__getitem__'",)
Traceback (most recent call last):
  File "/home/mej/.virtualenvs/bamboo/lib/python2.7/site-packages/celery/task/trace.py", line 224, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/mej/src/bamboo/bamboo/core/merge.py", line 48, in _merge_datasets_task
    in datasets]):
  File "/home/mej/src/bamboo/bamboo/models/dataset.py", line 62, in dataset_id
    return self.record[DATASET_ID]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by pld** [comment]
I can't replicate this, running celeryd and bamboo locally and hooking pybamboo up to my local version has everything looking fine.  Maybe closing another issue solved this?  Or maybe there's another test that will reveal it.  Closing for now.
