### ISSUE TITLE
Junked dataset if date parsing fails

### ISSUE THREAD

**Issue by rgaudin** [SEL-Columbia/bamboo#290]
if a column contains a data that looks like a date, bamboo will try to parse it and convert it into an internal Date object.

In the case of timezone aware (non UTC) ISO8601 formated date, the parser fails because of the “+” sign (which indicates the offset).

Instead of just not considering the data as a date, the dataset creation completes (and returns a dataset ID) but the dataset is wrong:
- No rows saved.
- No schema created.

Example CSV `data.csv`:

```
name,age,start_time
reg,30,2012-11-15T10:32:32.090+03
```

```
curl -X POST -F csv_file=@data.csv http://bamboo.io/datasets
{"id": "a3592c1b5a2149b8b24f195374852dcb"}
curl http://bamboo.io/datasets/a3592c1b5a2149b8b24f195374852dcb
[]
curl http://bamboo.io/datasets/a3592c1b5a2149b8b24f195374852dcb/info
{"num_rows": 0, "attribution": "", "description": "", "license": "", "num_columns": null, "updated_at": null, "created_at": "2012-11-23 18:57:09", "schema": null, "id": "a3592c1b5a2149b8b24f195374852dcb", "label": ""}reg@elb /tmp $ 
```

**Comment by pld** [comment]
This is apparently a problem that pandas has when getting the number of unique columns for ISO8601 dates:

``` python
Traceback (most recent call last):
  File "/home/bertrand/src/bamboo/bamboo/tests/controllers/test_datasets.py", line 950, in test_bad_date
    self._post_file('bad_date.csv')
  File "/home/bertrand/src/bamboo/bamboo/tests/controllers/test_abstract_datasets.py", line 46, in _post_file
    allow_local_file=True).dataset_id
  File "/home/bertrand/src/bamboo/bamboo/lib/io.py", line 44, in create_dataset_from_url
    call_async(import_dataset, dataset, filepath_or_buffer=url)
  File "/home/bertrand/src/bamboo/bamboo/lib/utils.py", line 59, in call_async
    function(*args, **kwargs)
  File "/home/bertrand/.virtualenvs/bamboo/lib/python2.7/site-packages/celery/app/task.py", line 323, in __call__
    return self.run(*args, **kwargs)
  File "/home/bertrand/src/bamboo/bamboo/lib/io.py", line 21, in import_dataset
    dataset.save_observations(dframe)
  File "/home/bertrand/src/bamboo/bamboo/models/dataset.py", line 339, in save_observations
    Observation().save(dframe, self)
  File "/home/bertrand/src/bamboo/bamboo/models/observation.py", line 89, in save
    dataset.build_schema(dframe)
  File "/home/bertrand/src/bamboo/bamboo/models/dataset.py", line 272, in build_schema
    schema = schema_from_data_and_dtypes(self, dframe)
  File "/home/bertrand/src/bamboo/bamboo/lib/schema_builder.py", line 82, in schema_from_data_and_dtypes
    name].nunique()
  File "/home/bertrand/.virtualenvs/bamboo/lib/python2.7/site-packages/pandas/core/series.py", line 1132, in nunique
    return len(self.value_counts())
  File "/home/bertrand/.virtualenvs/bamboo/lib/python2.7/site-packages/pandas/core/series.py", line 1111, in value_counts
    return value_counts(self.values, sort=True, ascending=False)
  File "/home/bertrand/.virtualenvs/bamboo/lib/python2.7/site-packages/pandas/core/algorithms.py", line 177, in value_counts
    result = Series(counter)
  File "/home/bertrand/.virtualenvs/bamboo/lib/python2.7/site-packages/pandas/core/series.py", line 333, in __new__
    data = [data.get(i, nan) for i in index]
  File "datetime.pyx", line 396, in pandas.lib._Timestamp.__richcmp__ (pandas/src/tseries.c:34544)
  File "datetime.pyx", line 470, in pandas.lib._Timestamp.to_datetime (pandas/src/tseries.c:35472)
  File "datetime.pyx", line 589, in pandas.lib.convert_to_tsobject (pandas/src/tseries.c:37289)
AttributeError: 'tzoffset' object has no attribute 'normalize'
```

I'm just going to catch the error and move on, which means no cardinality is reported for the column.  We can revisit that later but it will require a pandas fix, not bamboo.
