### ISSUE TITLE
Different datetime formats in a single column prevents DS creation

### ISSUE THREAD

**Issue by rgaudin** [SEL-Columbia/bamboo#299]
**_EDITED**_ Was: Unable to create dataset from CSV depending on # of rows 

Trying to create a dataset from a CSV, I encounter a problem with a reasonable CSV file of ~500 rows.
Dataset is created but never usable:
- `{"error": "dataset is not finished importing"}` returned by `/summary`
- `"num_rows": 0, "num_columns": 0, "updated_at": null, "schema": null}` in `/info`

Very same CSV file stripped to first 10 or 20 rows works fine.

Haven't check if there are variations in the data but error message seems to indicate a size issue.

@pld @mejymejy

**Comment by pld** [comment]
We have tests that create from large (> 1,000 and > 10,000 rows) datasets.  How many columns does the data have? I'd trying putting the dataset in one of the create from CSV tests and seeing what happens.  If that's inconclusive, you could tail the celery and server logs on production and see if there's anything suspivious happening.

If it's becuase of size, maybe it's very wide and the documents are too large for Mongo, or maybe it's eating up too much RAM.  Unless there's been a regression size handling I'd guess the problem is something else, we've been able to upload large Nigeria datasets (I forget the exact dims but largest around 45M) without issue.  Send us that dataset (or to the bamboo-dev list if it can be public) if your sleuthing doesn't turn anything up.

**Comment by rgaudin** [comment]
OK, As suggested it has nothing to do with size.
It is actually related to dates, again but it's different than #290 (although cause might be the same).

If a column contain different formats for datetime (or at least the two different forms bellow), it fails to create the dataset.
To test it, just save the following into a CSV file and try to create a dataset. If the dates were all the same format, it works.

```
start   end today   deviceid
2011-06-25T00:00:00.000000  2011-06-25T00:20:00.000000  2011-06-25T00:00:00.000000  n/a
2012-08-20T19:41:56.752+02  2011-06-25T00:20:00.000000  2011-06-25T00:00:00.000000  n/a
```

Since we are storing typeless data in formhub and that different devices (enketo, odk) report datetime differently, we are generating those files already and it prevents formhub csv file to make it to bamboo.

**Comment by pld** [comment]
I see, I misunderstood your previous comment.  This may be [our code](https://github.com/modilabs/bamboo/blob/master/bamboo/lib/datetools.py#L55) or it may be pandas, I'll look into how pandas handles the date parsing.

**Comment by pld** [comment]
The raw error:

``` python
Traceback (most recent call last):
  File "/home/leonhard/src/bamboo/bamboo/tests/controllers/test_datasets.py", line 622, in test_multiple_date_formats
    self._post_file('multiple_date_formats.csv')
  File "/home/leonhard/src/bamboo/bamboo/tests/controllers/test_abstract_datasets.py", line 54, in _post_file
    allow_local_file=True).dataset_id
  File "/home/leonhard/src/bamboo/bamboo/lib/io.py", line 41, in create_dataset_from_url
    call_async(import_dataset, dataset, filepath_or_buffer=url)
  File "/home/leonhard/src/bamboo/bamboo/lib/utils.py", line 62, in call_async
    function(*args, **kwargs)
  File "/home/leonhard/.virtualenvs/bamboo/lib/python2.7/site-packages/celery/app/task.py", line 315, in __call__
    return self.run(*args, **kwargs)
  File "/home/leonhard/src/bamboo/bamboo/lib/io.py", line 22, in import_dataset
    dataset.save_observations(dframe)
  File "/home/leonhard/src/bamboo/bamboo/models/dataset.py", line 365, in save_observations
    Observation().save(dframe, self)
  File "/home/leonhard/src/bamboo/bamboo/models/observation.py", line 80, in save
    dataset.build_schema(dframe)
  File "/home/leonhard/src/bamboo/bamboo/models/dataset.py", line 294, in build_schema
    new_schema = schema_from_data_and_dtypes(self, dframe)
  File "/home/leonhard/src/bamboo/bamboo/lib/schema_builder.py", line 81, in schema_from_data_and_dtypes
    name].nunique()
  File "/home/leonhard/.virtualenvs/bamboo/lib/python2.7/site-packages/pandas/core/series.py", line 1119, in nunique
    return len(self.value_counts())
  File "/home/leonhard/.virtualenvs/bamboo/lib/python2.7/site-packages/pandas/core/series.py", line 1098, in value_counts
    return value_counts(self.values, sort=True, ascending=False)
  File "/home/leonhard/.virtualenvs/bamboo/lib/python2.7/site-packages/pandas/core/algorithms.py", line 171, in value_counts
    result = Series(counter)
  File "/home/leonhard/.virtualenvs/bamboo/lib/python2.7/site-packages/pandas/core/series.py", line 316, in __new__
    index = Index(sorted(data))
TypeError: can't compare offset-naive and offset-aware datetimes
```

Will catch and pass this error.  May be an issue later if we want to take latest on inconsistent date columns.
