### ISSUE TITLE
Unable to create dataset from json_file

### ISSUE THREAD

**Issue by rgaudin** [SEL-Columbia/bamboo#463]
Right now, on bamboo.io, all attempts to create a dataset from a `json_file` fails.
I am trying to get bamboo setup right now so I don't have a full trace yet. celery log on server shows a completed task…

CSV imports are working.

**Comment by rgaudin** [comment]
OK, I have a trace now:

The request first: `curl -X POST -F json_file=@tests/fixtures/good_eats.json http://localhost:8080/datasets`

```
[19/Feb/2013:18:03:50] HTTP Traceback (most recent call last):
  File "/Volumes/data/src/envs/bamboo/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/Volumes/data/src/envs/bamboo/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Volumes/data/src/envs/bamboo/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "bamboo/controllers/datasets.py", line 274, in create
    dataset.import_from_json(json_file)
  File "bamboo/lib/io.py", line 103, in import_from_json
    partial(file_reader, content))
  File "bamboo/lib/async.py", line 29, in call_async
    countdown=countdown, args=args, kwargs=kwargs)
  File "/Volumes/data/src/envs/bamboo/lib/python2.7/site-packages/celery/app/task.py", line 478, in apply_async
    **options)
  File "/Volumes/data/src/envs/bamboo/lib/python2.7/site-packages/celery/app/amqp.py", line 244, in publish_task
    **kwargs
  File "/Volumes/data/src/envs/bamboo/lib/python2.7/site-packages/kombu/messaging.py", line 157, in publish
    compression, headers)
  File "/Volumes/data/src/envs/bamboo/lib/python2.7/site-packages/kombu/messaging.py", line 233, in _prepare
    body) = encode(body, serializer=serializer)
  File "/Volumes/data/src/envs/bamboo/lib/python2.7/site-packages/kombu/serialization.py", line 161, in encode
    payload = encoder(data)
  File "/Volumes/data/src/envs/bamboo/lib/python2.7/site-packages/kombu/serialization.py", line 340, in dumps
    return dumper(obj, protocol=pickle_protocol)
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

[19/Feb/2013:18:03:50] HTTP
Request Headers:
  Content-Length: 293
  HOST: localhost:8080
  EXPECT: 100-continue
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8r zlib/1.2.5
  Content-Type: multipart/form-data; boundary=----------------------------daa3e186fe40
127.0.0.1 - - [19/Feb/2013:18:03:50] "POST /datasets HTTP/1.1" 500 2553 "" "curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8r zlib/1.2.5"
```
