### ISSUE TITLE
'Proxy' object has no attribute 'apply_async'

### ISSUE THREAD

**Issue by rgaudin** [SEL-Columbia/bamboo#503]
Everytime I try to create a dataset from a large JSON file it fails with the following trace.
It might be due to my JSON files since a super simple ones works.

```
[2013-03-17 19:12:59,737: ERROR/MainProcess] Task bamboo.lib.io.import_dataset[56a88e06-33dd-40b1-a474-f83c7026ad0e] raised exception: AttributeError("'Proxy' object has no attribute 'apply_async'",)
Traceback (most recent call last):
  File "/Volumes/data/src/envs/bamboo/lib/python2.7/site-packages/celery/task/trace.py", line 224, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Volumes/data/src/envs/bamboo/lib/python2.7/site-packages/celery/task/trace.py", line 407, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Volumes/data/src/modi/bamboo/bamboo/lib/io.py", line 34, in import_dataset
    dataset.delete(countdown=86400)
  File "/Volumes/data/src/modi/bamboo/bamboo/models/dataset.py", line 288, in delete
    call_async(delete_task, self, countdown=countdown)
  File "/Volumes/data/src/modi/bamboo/bamboo/lib/async.py", line 28, in call_async
    function.__getattribute__('apply_async')(
AttributeError: 'Proxy' object has no attribute 'apply_async'
```

[Example file](http://depositfiles.com/files/rkdqp9ig3)

**Comment by pld** [comment]
An exception is being caught, then `lib/io` line 34 is trying to delete a dataset that's in a bad state.  We catch this exception so that we can log it, but here the logging fails and the underlying exception is being hidden.

The logging failure appears related to a problem calling celery, you might want to try turning aync off, see `lib/async.set_async`.

Perhaps simpler, just to see the full exception, you could add,

``` python
print e.__str__()
```

before the current line 34.

Or, to see the underlying exception, you might want to remove the try/except, remove lines 26 and 29-34, so that the `lib/io.import_dataset` function looks like,

``` python
dframe = file_reader()
dataset.save_observations(dframe)
```

without a catch the underlying exception should be raised.

**Comment by rgaudin** [comment]
OK, thanks. The real exception is `InvalidDocument: key '$date' must not start with '$'`

This must be because I have stuff like `"created": {"$date": 1348611772000}` which comes from a bamboo export. I'll transform it but would we want to be able to resubmit an exported JSON to bamboo?

**Comment by pld** [comment]
I think we may want to be able to resubmit a bamboo export, or we could
stipulate that clients use the CSV if they want something resubmittable.  I
guess the date field in that format is a Mongo default? Is separating the
date field like that useful in any way?  Let's open a new issue if you
think the format should change.
